@port = 2000
@baseUrl = http://localhost:{{port}}
@goalId = 69d93444b5643285a4beac61

### Get all goals
GET {{baseUrl}}/goals

### Get goal by id
GET {{baseUrl}}/goals/{{goalId}}

### Create a new goal
POST {{baseUrl}}/goals HTTP/1.1
Content-Type: application/json

{
  "userId": "69d3e2645c93244b93389617",
  "calories": 2700,
  "protein": 180,
  "carbs": 220,
  "fat": 60
}

### Update a goal by id
PUT {{baseUrl}}/goals/69d93a2ac8c6bf3b3de88619 HTTP/1.1
Content-Type: application/json

{
  "userId": "69d3e2645c93244b93389617",
  "calories": 2100
}

### Delete a goal by id
DELETE {{baseUrl}}/goals/69d93a2ac8c6bf3b3de88619